import type { DataSummary } from "./supabase";

/**
 * PRD §7.1: "Red-flag bypass runs before the model path." A hard-coded rule
 * set checks every inbound message for emergency language before the model
 * is ever invoked. Deliberately dumb, deliberately first, deliberately not
 * an LLM classifier — a missed red flag here is not a UX bug, it's a safety
 * incident, so this stays a plain substring check with no ambiguity in its
 * own logic.
 */
const RED_FLAG_PATTERNS = [
  "chest pain",
  "can't breathe",
  "cant breathe",
  "cannot breathe",
  "difficulty breathing",
  "trouble breathing",
  "face drooping",
  "arm weakness",
  "slurred speech",
  "sudden numbness",
  "sudden confusion",
  "sudden severe headache",
  "can't move my",
  "cant move my",
  "passed out",
  "fainted",
  "fainting",
  "suicidal",
  "kill myself",
  "want to die",
];

export function isRedFlag(text: string): boolean {
  const normalized = text.toLowerCase();
  return RED_FLAG_PATTERNS.some((pattern) => normalized.includes(pattern));
}

/**
 * Fixed NHS guidance — direct, calm, no metaphors, per PRD §7.1 and the voice
 * rules in §14. Never generated by the model.
 */
export const RED_FLAG_RESPONSE =
  "This sounds urgent. Please call 999 now, or 111 if it feels less severe. " +
  "Homie can't help with this — a person needs to, right now.";

export type SafetyCommand = "stop" | "delete" | "my_data";

/**
 * PRD §7.3: STOP, DELETE and MY DATA must work — exact-match (not substring)
 * so an ordinary sentence that happens to contain "stop" ("the pain won't
 * stop") never triggers an opt-out.
 */
export function classifyCommand(text: string): SafetyCommand | null {
  const normalized = text.trim().toLowerCase().replace(/[.!?]+$/, "");
  if (normalized === "stop" || normalized === "unsubscribe") return "stop";
  if (normalized === "delete" || normalized === "delete my data") return "delete";
  if (normalized === "my data" || normalized === "mydata") return "my_data";
  return null;
}

export const STOP_RESPONSE = "You're unsubscribed — Homie won't text you again unless you message first.";

export const DELETE_RESPONSE =
  "Done. Your check-ins and replies have been deleted. This can't be undone.";

export function myDataResponseText(summary: DataSummary): string {
  const since = summary.first_checkin_at ? new Date(summary.first_checkin_at).toLocaleDateString("en-GB") : null;
  const consent = summary.consent_at ? new Date(summary.consent_at).toLocaleDateString("en-GB") : "not yet recorded";
  const history = since
    ? `${summary.checkins_count} check-in${summary.checkins_count === 1 ? "" : "s"} since ${since}`
    : "no check-ins yet";
  return (
    `Here's what Homie holds on ${summary.phone}: ${history}. Consent recorded: ${consent}. ` +
    "Reply DELETE to erase it all, or STOP to unsubscribe."
  );
}
